repos:
- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0               # use the most recent version
  hooks:
  - id: clang-format
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
  - id: cmake-format